### ISSUE TITLE
Sample App: Resource Not Found Exception

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [gowong/material-sheet-fab#17]
I keep getting this:
 FATAL EXCEPTION: main
                                                                                      Process: com.gordonwong.materialsheetfab.sample, PID: 3563
                                                                                      android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                                          at android.content.res.Resources.getValue(Resources.java:1351)
                                                                                          at android.content.res.Resources.getDrawable(Resources.java:804)
                                                                                          at android.content.Context.getDrawable(Context.java:458)
                                                                                          at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
                                                                                          at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:321)
                                                                                          at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:177)
                                                                                          at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:170)
                                                                                          at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:53)
                                                                                          at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:74)
                                                                                          at com.gordonwong.materialsheetfab.sample.adapters.NotesAdapter.onBindViewHolder(NotesAdapter.java:52)
                                                                                          at com.gordonwong.materialsheetfab.sample.adapters.NotesAdapter.onBindViewHolder(NotesAdapter.java:22)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5212)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5245)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4483)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
                                                                                          at android.support.v7.widget.LayoutState.next(LayoutState.java:86)
                                                                                          at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1423)
                                                                                          at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:610)
                                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                                          at android.view.View.layout(View.java:16630)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                          at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
                                                                                          at android.view.View.layout(View.java:16630)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                          at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
                                                                                          at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
                                                                                          at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                          at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1133)
                                                                                          at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
                                                                                          at android.view.View.layout(View.java:16630)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                          at android.view.View.layout(View.java:16630)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                          at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
                                                                                          at android.view.View.layout(View.java:16630)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                          at android.view.View.layout(View.java:16630)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                          at android.view.View.layout(View.java:16630)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                          at android.view.View.layout(View.java:16630)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                      	at

**Comment by gowong** [comment]
Yeah, looks like a bug in the sample app where it's missing a check when setting a note's icon.
In NotesAdapter, should be:
```java
if (infoImage == 0) {
    holder.infoImageView.setVisibility(View.INVISIBLE);
} else {
    holder.infoImageView.setImageResource(infoImage);
    holder.infoImageView.setVisibility(View.VISIBLE);
}
```

**Comment by AndroidDeveloperLB** [comment]
The weird thing is that it worked fine at another PC. and yet when I cloned the project at home, it didn't...

**Comment by AndroidDeveloperLB** [comment]
It crashed on the emulator for me.

**Comment by gowong** [comment]
Were both emulators running the same version of Android?

**Comment by AndroidDeveloperLB** [comment]
Emulator at home (android 6), device at the office.

**Comment by AndroidDeveloperLB** [comment]
Speaking of android versions, since support library and design library support lower versions, can you please provide a fallback for older ones? Even a simple popup and hiding of the FAB can be nice...

**Comment by gowong** [comment]
Was both the device and the emulator running Android 6?
API levels >= 14 are supported. Are you looking to support version older than that?

**Comment by AndroidDeveloperLB** [comment]
I think I've tested on 2 Nexus 4 devices: One with Kitkat and one with Lollipop.
About API level, I think it's best to match the same levels as the ones of the support libraries.
